### PR TITLE
Fixed the markdown issue

### PR DESCRIPTION
**Pull request by KrishAgarwal2811**

### CODE REVIEW

**Comment by almostSouji** [comment]
what issue is this supposed to solve? the current approach seems to work fine for me

**Comment by thehairy** [comment]
Also not sure, the command seems to be working fine, as well as the markdown.

**Comment by NotSugden** [comment]
image

on mobile the markdown needs to be outside the hyperlink text to render correctly

**Comment by KrishAgarwal2811** [comment]
> Also not sure, the command seems to be working fine, as well as the markdown.

Yeah the markdown works well on PC (I don't know about Mac / IPhone) but I doesn't work in Android. 

Relevant Image: 
discord screenshot 
By another discord user.

**Review by almostSouji — CHANGES_REQUESTED** [review]
needs to be addressed in other commands as well

**Comment by almostSouji** [comment]
superseded by #27 with a cleaner solution

**Pull request closed without merging**
