### PR TITLE
feat: add limits tag

### PR DESCRIPTION
**Pull request by Wolvinny**

### CODE REVIEW

**Comment by jaw0r3k** [comment]
Why not to use separate tags?

**Comment by Wolvinny** [comment]
> Why not to use separate tags?

Its easier to just bundle them all in 1 'limits' tag instead of 3 different ones

**Comment by megatank58** [comment]
Having them seperated is lesser of a text wall though, practically one would generally never need the three of them together either

**Review by almostSouji — CHANGES_REQUESTED** [review]
that indeed looks chunkier than expected
image
thinking we we should just chuck it all into one line (maybe even more compact by omitting the "limit" in each entry, as it is contextualized by the heading), or use separate tags as suggested above
IMO either works

**Comment by jaw0r3k** [comment]
i am not a fan, its just a chunk of text 
also you should format the file

**Pull request closed without merging**
