### PR TITLE
tag(replit): nodejs v16

### PR DESCRIPTION
**Pull request by xHyroM**
I've added a tag on how to install nodejs v16 on replit. A lot of people are asking this at the moment because of djs v13, and a lot of people are saying that it can't be done, but it's very easy.

### CODE REVIEW

**Comment by thehairy** [comment]
"Replit currently only supports v12"
Thats the point, thats why everyone says that.

We don't need that. That just gives people hope and they will continue to use replit as a host. Nobody wants that.

**Comment by xHyroM** [comment]
> 
> 
> "Replit currently only supports v12"
> Thats the point, thats why everyone says that.
> 
> We don't need that. That just gives people hope and they will continue to use replit as a host. Nobody wants that.

Right now replit doesn't support nodejs v12 yet, but you can download it. People say it's not possible at all. And honestly, I think replit is plenty enough to use some private bot for 1 server. Better than glitch.

**Comment by thehairy** [comment]
> > "Replit currently only supports v12"
> > Thats the point, thats why everyone says that.
> > We don't need that. That just gives people hope and they will continue to use replit as a host. Nobody wants that.
> 
> Right now replit doesn't support nodejs v12 yet, but you can download it. People say it's not possible at all. And honestly, I think replit is plenty enough to use some private bot for 1 server. Better than glitch.

And why would that be tag worthy?

**Comment by xHyroM** [comment]
> 
> 
> > > "Replit currently only supports v12"
> > > Thats the point, thats why everyone says that.
> > > We don't need that. That just gives people hope and they will continue to use replit as a host. Nobody wants that.
> > 
> > 
> > Right now replit doesn't support nodejs v12 yet, but you can download it. People say it's not possible at all. And honestly, I think replit is plenty enough to use some private bot for 1 server. Better than glitch.
> 
> And why would that be tag worthy?

A lot of people host on replite, and a lot of people also ask on the discord server why they have this error with `??`. I've answered about 20 people who said it's impossible. That's why I think this tag could bring usefulness. I'm tired of typing this all the time and people wouldn't write back that it can't be done, they would use the tag.

**Comment by almostSouji** [comment]
We are not repl.it support, this is by all means quite the hack, the message itself is quite chunky and disruptive when being used.

**Pull request closed without merging**
