### PR TITLE
chore(tags): anchored links are supported in message content

### PR DESCRIPTION
**Pull request by Syjalo**

### CODE REVIEW

**Comment by Jiralite** [comment]
If this is done due to the markdown update, we should probably expand to cover them all. For example, replacing "•" with "-".

**Comment by Syjalo** [comment]
The `markdown` tag is there

**Comment by almostSouji** [comment]
discord has released markdown in some servers without anchored links - pending further updates

**Comment by GodderE2D** [comment]
> discord has released markdown in some servers without anchored links - pending further updates

This has now been rolled out to all servers since June 29.

**Review by almostSouji — APPROVED** [review]

**Pull request merged**
