### PR TITLE
feat(tags): versioned tags

### PR DESCRIPTION
**Pull request by MrMythicalYT**
Implements #125

### CODE REVIEW

**Comment by MrMythicalYT** [comment]
Should the tags be converted with this PR? And should the version default be based on the channel, or just a hard-coded version?

**Comment by almostSouji** [comment]
not really convinced this adds a whole lot of value

**Comment by MrMythicalYT** [comment]
I believe it would, mostly for the tags with code samples (like `embed-files`)

**Comment by megatank58** [comment]
this feels like a lot of configuration for tags which can just be seperated for two versions and maintained seperately if needed

**Pull request closed without merging**
